version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RUST_BACKTRACE=1
      - DATABASE_URL=postgres://user:password@db:5432/sophisticate_phrase_db
    depends_on:
      db:
        condition: service_healthy
    
    volumes:
      - .:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sophisticate_phrase_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sophisticate_phrase_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  cargo_cache:
  target_cache: